services:
  - type: worker
    name: mexc-autotrader
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: OWNER_USER_ID
        sync: false
      - key: MEXC_API_KEY
        sync: false
      - key: MEXC_API_SECRET
        sync: false
      - key: DRY_RUN
        value: "True"
      - key: MARGIN_USDT
        value: "50"
      - key: LEVERAGE
        value: "20"
      - key: ALLOW_SLIPPAGE_PCT
        value: "0.30"
      - key: TZ
        value: "Europe/Vienna"
